version: "3.8"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/coder
        depends_on:
            - redis
        links:
            - db
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: carford_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: cardford
            MYSQL_PASSWORD: cardford123
        volumes:
            - ../app/db:/docker-entrypoint-initdb.d/:ro
    redis:
        image: redis